#!/usr/bin/env bash
docker run --name rtl-app-testnet -d --restart unless-stopped --network bitcoind-testnet --ip 10.0.0.5 -p 33000:33000 -v $PWD/shares/testnet/rtl-config:/root/rtl  -v $PWD/shares/testnet/dot-lightning:/root/.lightning:ro -v $PWD/shares/testnet/lightning-api-certs:/root/lightning-api-certs:ro rtl-app
