#!/usr/bin/env bash
docker run --name lightningd -d --restart unless-stopped --network bitcoin-main --ip 10.0.0.3 -p 9735:9735 -p 3001:3001 -v $PWD/shares/dot-lightning:/root/.lightning -v /media/ln-backup:/ln-backup -v /TIMECHAIN:/root/.bitcoin:ro lightningd
