#!/usr/bin/env bash

if [ $# -eq 0 ]
  then
    echo "Rune parameter missing."
    echo
    echo "Use the following command to create a rune:"
    echo
    echo "./scripts/lightning-cli createrune"
    echo
    echo "Currently available runes (showrunes output):"
    echo
    source $(dirname "$0")/lightning-cli showrunes --human-readable --filter='{"runes":[{"rune":true}]}'
    exit 1
fi

docker run --rm --network bitcoin-main curlimages/curl -s -X 'POST' \
  'http://10.0.0.3:3001/v1/getinfo' \
  -H 'accept: application/json' \
  -H "Rune: $1"
