#!/usr/bin/env bash
docker run --name lightning-api -d --restart unless-stopped -e PROTOCOL=http -p 3001:3001 -p 4001:4001 -v $PWD/shares/dot-lightning:/root/.lightning -v $PWD/shares/lightning-api-certs:/root/c-lightning-REST/certs lightning-api
