#!/usr/bin/env bash
docker run --name rtl-app -d --restart unless-stopped --network bitcoind  --ip 10.1.0.5 -p 3000:3000 -v $PWD/shares/rtl-config:/root/rtl -v $PWD/shares/dot-lightning:/root/.lightning:ro -v $PWD/shares/lightning-api-certs:/root/lightning-api-certs:ro rtl-app
